#!/usr/bin/env python

import sys
import envpickler
from subprocess import call
from argparse import ArgumentParser

parser = ArgumentParser(usage="%(prog)s [options] command")
parser.add_argument('-e', '--env', required=True,
                    help="the name of the environment")
args, user_args = parser.parse_known_args()

status = envpickler.load(args.env)
if not status:
    sys.exit(1)

if len(user_args) == 1:
    user_args = user_args[0].split()

call(user_args)
